# Assignment 3

<h3>Create a Company Dataframe</h3>


In [1]:
import numpy as np
import pandas as pd

In [2]:
# create a dataframe of various company
data = {'Company' : ['Amazon', 'IBM', 'CTS', 'Amazon', 'TCS', 'IBM', 'TCS', 'Amazon','CTS'], 
            'Person' : ['Priyanka', 'Punit', 'Rashmi', 'Anupam', 'Mayank', 'Prerna', 'Prerak', 'Rohit', 'Neha'] ,
            'Sales(in $)' : [2000, 800, 900, 700, 1200, 1000, 600, 1600, 1000]}
comp_data = pd.DataFrame(data)
comp_data

Company    Person  Sales(in $)
0  Amazon  Priyanka         2000
1     IBM     Punit          800
2     CTS    Rashmi          900
3  Amazon    Anupam          700
4     TCS    Mayank         1200
5     IBM    Prerna         1000
6     TCS    Prerak          600
7  Amazon     Rohit         1600
8     CTS      Neha         1000

In [3]:
# find the sales of each company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).sum()

Company
Amazon    4300
CTS       1900
IBM       1800
TCS       1800
Name: Sales(in $), dtype: int64

In [4]:
#find first row of each company
co = comp_data.groupby('Company')
co.first()

Person  Sales(in $)
Company                       
Amazon   Priyanka         2000
CTS        Rashmi          900
IBM         Punit          800
TCS        Mayank         1200

In [5]:
#find the average sales of the company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).mean()

Company
Amazon    1433.333333
CTS        950.000000
IBM        900.000000
TCS        900.000000
Name: Sales(in $), dtype: float64

In [6]:
#find the and minimum sales of the company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).min()

Company
Amazon    700
CTS       900
IBM       800
TCS       600
Name: Sales(in $), dtype: int64

In [7]:
#find the maximum sales of the company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).max()

Company
Amazon    2000
CTS       1000
IBM       1000
TCS       1200
Name: Sales(in $), dtype: int64

In [8]:
#show the count of person of each company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).count()

Company
Amazon    3
CTS       2
IBM       2
TCS       2
Name: Sales(in $), dtype: int64

In [9]:
#show the description of each company
comp_data['Sales(in $)'].groupby([comp_data['Company']]).describe()

count         mean         std    min     25%     50%     75%     max
Company                                                                       
Amazon     3.0  1433.333333  665.832812  700.0  1150.0  1600.0  1800.0  2000.0
CTS        2.0   950.000000   70.710678  900.0   925.0   950.0   975.0  1000.0
IBM        2.0   900.000000  141.421356  800.0   850.0   900.0   950.0  1000.0
TCS        2.0   900.000000  424.264069  600.0   750.0   900.0  1050.0  1200.0

In [10]:
#show the description in vertical manner
comp_data['Sales(in $)'].groupby([comp_data['Company']]).describe().transpose()

Company       Amazon          CTS          IBM          TCS
count       3.000000     2.000000     2.000000     2.000000
mean     1433.333333   950.000000   900.000000   900.000000
std       665.832812    70.710678   141.421356   424.264069
min       700.000000   900.000000   800.000000   600.000000
25%      1150.000000   925.000000   850.000000   750.000000
50%      1600.000000   950.000000   900.000000   900.000000
75%      1800.000000   975.000000   950.000000  1050.000000
max      2000.000000  1000.000000  1000.000000  1200.000000

In [11]:
#Rename Sales Column


<h3> Create 1D Array</h3>

In [12]:
one_array = np.array([1,2,3])
one_array

array([1, 2, 3])

In [13]:
#show the type of array
one_array.dtype

dtype('int32')

In [14]:
# show the size of the array
one_array.size

3

In [15]:
#show the dimension of array
one_array.ndim

1

<h3>Create 2D Array</h3>

In [16]:
two_array = np.array([[1,2,4], [4,6,8], [7,8,0]])
two_array

array([[1, 2, 4],
       [4, 6, 8],
       [7, 8, 0]])

In [17]:
# type of array
two_array.dtype

dtype('int32')

In [18]:
# show the size of the array
two_array.size

9

In [19]:
#show the dimension of array
two_array.ndim

2

<h3>Create 3D Array</h3>

In [20]:
three_array = np.array([[[1,2,4],[4,6,8],[7,8,9]]])
three_array

array([[[1, 2, 4],
        [4, 6, 8],
        [7, 8, 9]]])

In [21]:
# type of array
three_array.dtype

dtype('int32')

In [22]:
# show the size of the array
three_array.size

9

In [23]:
#show the dimension of array
three_array.ndim

3

# Second Half

q. 
1. Add extra 5 rows and 1 column(sales variance) to the existing company dataset. 
2. Show unique company name.
3. Fetch that name where comp = TCS and sales >1000.
4. Fetch those rows where company name starts with T and Sales <1000.
5. Add one more column (Last Year Sales, Sales Vairance).

In [24]:
comp_data.head()


Company    Person  Sales(in $)
0  Amazon  Priyanka         2000
1     IBM     Punit          800
2     CTS    Rashmi          900
3  Amazon    Anupam          700
4     TCS    Mayank         1200

In [25]:
comp_data = comp_data.append(pd.DataFrame({'Company':['IBM','Capgemini','Persistent'], 'Person':['Dujul Kumari', 'Nikhil Kumar', 'Man C'], 'Sales(in $)':[800,1100,1010]}), ignore_index=True)

In [26]:
comp_data

Company        Person  Sales(in $)
0       Amazon      Priyanka         2000
1          IBM         Punit          800
2          CTS        Rashmi          900
3       Amazon        Anupam          700
4          TCS        Mayank         1200
5          IBM        Prerna         1000
6          TCS        Prerak          600
7       Amazon         Rohit         1600
8          CTS          Neha         1000
9          IBM  Dujul Kumari          800
10   Capgemini  Nikhil Kumar         1100
11  Persistent         Man C         1010

In [27]:
comp_data = comp_data.append(pd.DataFrame({'Company':['TCS', 'Capegemini'], 'Person':['Ashutosh', 'Aniket kr.'], 'Sales(in $)':[None,1400]}),ignore_index=True)

In [28]:
comp_data

Company        Person  Sales(in $)
0       Amazon      Priyanka       2000.0
1          IBM         Punit        800.0
2          CTS        Rashmi        900.0
3       Amazon        Anupam        700.0
4          TCS        Mayank       1200.0
5          IBM        Prerna       1000.0
6          TCS        Prerak        600.0
7       Amazon         Rohit       1600.0
8          CTS          Neha       1000.0
9          IBM  Dujul Kumari        800.0
10   Capgemini  Nikhil Kumar       1100.0
11  Persistent         Man C       1010.0
12         TCS      Ashutosh          NaN
13  Capegemini    Aniket kr.       1400.0

In [29]:
comp_data.columns = [column.replace(' ','_') for column in comp_data.columns]

In [30]:
comp_data['Company'].unique()

array(['Amazon', 'IBM', 'CTS', 'TCS', 'Capgemini', 'Persistent',
       'Capegemini'], dtype=object)

In [31]:
comp_data = comp_data.rename(columns={'Sales(in_$)':'Sales'})
comp_data


Company        Person   Sales
0       Amazon      Priyanka  2000.0
1          IBM         Punit   800.0
2          CTS        Rashmi   900.0
3       Amazon        Anupam   700.0
4          TCS        Mayank  1200.0
5          IBM        Prerna  1000.0
6          TCS        Prerak   600.0
7       Amazon         Rohit  1600.0
8          CTS          Neha  1000.0
9          IBM  Dujul Kumari   800.0
10   Capgemini  Nikhil Kumar  1100.0
11  Persistent         Man C  1010.0
12         TCS      Ashutosh     NaN
13  Capegemini    Aniket kr.  1400.0

In [32]:
comp_data.query('Company == "TCS" and Sales>1000')

Company  Person   Sales
4     TCS  Mayank  1200.0

In [33]:
comp_data[comp_data.Company.str.startswith('T')].query('Sales<1000')

Company  Person  Sales
6     TCS  Prerak  600.0

In [34]:
comp_data['LYS'] = [1900,900,1000,1500,1100,1100,700,1600,900,700,1000,1000,None,0]

In [35]:
comp_data

Company        Person   Sales     LYS
0       Amazon      Priyanka  2000.0  1900.0
1          IBM         Punit   800.0   900.0
2          CTS        Rashmi   900.0  1000.0
3       Amazon        Anupam   700.0  1500.0
4          TCS        Mayank  1200.0  1100.0
5          IBM        Prerna  1000.0  1100.0
6          TCS        Prerak   600.0   700.0
7       Amazon         Rohit  1600.0  1600.0
8          CTS          Neha  1000.0   900.0
9          IBM  Dujul Kumari   800.0   700.0
10   Capgemini  Nikhil Kumar  1100.0  1000.0
11  Persistent         Man C  1010.0  1000.0
12         TCS      Ashutosh     NaN     NaN
13  Capegemini    Aniket kr.  1400.0     0.0

In [36]:
def func(x,y):
    
    if(y!= None and y!=0):
        return((x-y)/y)
    
    return y

comp_data['Variance'] = comp_data.apply(lambda x:func(x['Sales'],x['LYS']),axis=1)

comp_data

Company        Person   Sales     LYS  Variance
0       Amazon      Priyanka  2000.0  1900.0  0.052632
1          IBM         Punit   800.0   900.0 -0.111111
2          CTS        Rashmi   900.0  1000.0 -0.100000
3       Amazon        Anupam   700.0  1500.0 -0.533333
4          TCS        Mayank  1200.0  1100.0  0.090909
5          IBM        Prerna  1000.0  1100.0 -0.090909
6          TCS        Prerak   600.0   700.0 -0.142857
7       Amazon         Rohit  1600.0  1600.0  0.000000
8          CTS          Neha  1000.0   900.0  0.111111
9          IBM  Dujul Kumari   800.0   700.0  0.142857
10   Capgemini  Nikhil Kumar  1100.0  1000.0  0.100000
11  Persistent         Man C  1010.0  1000.0  0.010000
12         TCS      Ashutosh     NaN     NaN       NaN
13  Capegemini    Aniket kr.  1400.0     0.0  0.000000

q.

1. Set that dataframe descendingly by sales variance check whether null value is there or not if any null vlalue is there drop that row and store it in another df.

2. show the sum row wise and column wise in 3d array.

In [37]:
comp_data.sort_values("Variance",axis=0,ascending=False,inplace=True)

In [38]:
comp_data

Company        Person   Sales     LYS  Variance
9          IBM  Dujul Kumari   800.0   700.0  0.142857
8          CTS          Neha  1000.0   900.0  0.111111
10   Capgemini  Nikhil Kumar  1100.0  1000.0  0.100000
4          TCS        Mayank  1200.0  1100.0  0.090909
0       Amazon      Priyanka  2000.0  1900.0  0.052632
11  Persistent         Man C  1010.0  1000.0  0.010000
7       Amazon         Rohit  1600.0  1600.0  0.000000
13  Capegemini    Aniket kr.  1400.0     0.0  0.000000
5          IBM        Prerna  1000.0  1100.0 -0.090909
2          CTS        Rashmi   900.0  1000.0 -0.100000
1          IBM         Punit   800.0   900.0 -0.111111
6          TCS        Prerak   600.0   700.0 -0.142857
3       Amazon        Anupam   700.0  1500.0 -0.533333
12         TCS      Ashutosh     NaN     NaN       NaN

In [39]:
comp_data[comp_data['Variance'].isnull()]

Company    Person  Sales  LYS  Variance
12     TCS  Ashutosh    NaN  NaN       NaN

In [40]:
comp_data2 = comp_data[comp_data['Variance'].isnull()]


In [41]:
# Getting index of the 'Variance'= Nan rows
comp_data[comp_data['Variance'].isnull()].index

Int64Index([12], dtype='int64')

In [42]:
comp_data.drop(index = comp_data[comp_data['Variance'].isnull()].index , inplace= True )

In [43]:
# Nan Value deleted table
comp_data

Company        Person   Sales     LYS  Variance
9          IBM  Dujul Kumari   800.0   700.0  0.142857
8          CTS          Neha  1000.0   900.0  0.111111
10   Capgemini  Nikhil Kumar  1100.0  1000.0  0.100000
4          TCS        Mayank  1200.0  1100.0  0.090909
0       Amazon      Priyanka  2000.0  1900.0  0.052632
11  Persistent         Man C  1010.0  1000.0  0.010000
7       Amazon         Rohit  1600.0  1600.0  0.000000
13  Capegemini    Aniket kr.  1400.0     0.0  0.000000
5          IBM        Prerna  1000.0  1100.0 -0.090909
2          CTS        Rashmi   900.0  1000.0 -0.100000
1          IBM         Punit   800.0   900.0 -0.111111
6          TCS        Prerak   600.0   700.0 -0.142857
3       Amazon        Anupam   700.0  1500.0 -0.533333

In [44]:
array = comp_data[['Sales','LYS']].values

In [45]:
row_sum = array.sum(axis=1)


In [46]:
print(row_sum)


[1500. 1900. 2100. 2300. 3900. 2010. 3200. 1400. 2100. 1900. 1700. 1300.
 2200.]


In [47]:
array = np.hstack((array,row_sum.reshape(len(row_sum),1)))

In [48]:
col_sum = array.sum(axis=0)
array = np.vstack((array, [col_sum]))

In [49]:
array

array([[  800.,   700.,  1500.],
       [ 1000.,   900.,  1900.],
       [ 1100.,  1000.,  2100.],
       [ 1200.,  1100.,  2300.],
       [ 2000.,  1900.,  3900.],
       [ 1010.,  1000.,  2010.],
       [ 1600.,  1600.,  3200.],
       [ 1400.,     0.,  1400.],
       [ 1000.,  1100.,  2100.],
       [  900.,  1000.,  1900.],
       [  800.,   900.,  1700.],
       [  600.,   700.,  1300.],
       [  700.,  1500.,  2200.],
       [14110., 13400., 27510.]])