# Machine Learning using python


<center><h2> Assignment 2 </h2></center>

1. Create a sample dataset, import it into python and show the top 10 rows.

In [3]:
import numpy as np
import pandas as pd

In [12]:
dataset  = pd.read_csv('D:\Open Source data\Global_Temperature\Global_Temperature_data.csv')
dataset.head(10)

Year   min   max
0  1880 -0.19 -0.11
1  1881 -0.10 -0.14
2  1882 -0.10 -0.17
3  1883 -0.19 -0.21
4  1884 -0.28 -0.24
5  1885 -0.31 -0.26
6  1886 -0.32 -0.27
7  1887 -0.35 -0.27
8  1888 -0.18 -0.27
9  1889 -0.11 -0.26

In [11]:
X = dataset.iloc[0:10 , :].values

print(X)

[[ 1.880e+03 -1.900e-01 -1.100e-01]
 [ 1.881e+03 -1.000e-01 -1.400e-01]
 [ 1.882e+03 -1.000e-01 -1.700e-01]
 [ 1.883e+03 -1.900e-01 -2.100e-01]
 [ 1.884e+03 -2.800e-01 -2.400e-01]
 [ 1.885e+03 -3.100e-01 -2.600e-01]
 [ 1.886e+03 -3.200e-01 -2.700e-01]
 [ 1.887e+03 -3.500e-01 -2.700e-01]
 [ 1.888e+03 -1.800e-01 -2.700e-01]
 [ 1.889e+03 -1.100e-01 -2.600e-01]]


2. Create a dataframe with name, dept, roll. Add 10 rows of data in it. Convert it into a dataframe.
Add 2 columns cgpa1  and cgpa2. 
show the 3rd row.
Display the students with marks >80.
Show first 5 and last 2 rows of the dataframe.
Show marks column.
From cgpa1 and cgpa2 find ygpa

In [14]:
frame = {'name':[], 'dept':[], 'roll':[]}

for i in range(1,11):
    frame['name'].append(input())
    frame['dept'].append(input())
    frame['roll'].append(int(input()))
    

Anupam
IT
55
PB
IT
27
PJ
IT
25
DK
IT
27
MS
36
36
Prerna
IT
26
KV
IT
40
pC
IT
28
SV
IT
4
MB
IT
37


In [15]:
print(frame)

{'name': ['Anupam', 'PB', 'PJ', 'DK', 'MS', 'Prerna', 'KV', 'pC', 'SV', 'MB'], 'roll': [55, 27, 25, 27, 36, 26, 40, 28, 4, 37], 'dept': ['IT', 'IT', 'IT', 'IT', '36', 'IT', 'IT', 'IT', 'IT', 'IT']}


In [16]:
dataframe =  pd.DataFrame.from_dict(frame)

In [17]:
dataframe

dept    name  roll
0   IT  Anupam    55
1   IT      PB    27
2   IT      PJ    25
3   IT      DK    27
4   36      MS    36
5   IT  Prerna    26
6   IT      KV    40
7   IT      pC    28
8   IT      SV     4
9   IT      MB    37

In [19]:
dataframe.iloc[2,:]

dept    IT
name    PJ
roll    25
Name: 2, dtype: object

In [25]:
dataframe.insert(loc=3,column='cgpa1',value = [9,9,9,9,8,8,8,7.5,7.5,7.5])

In [27]:
dataframe.insert(loc=3,column='cgpa2',value = [9.2,9.2,9.3,9.6,8.9,8.8,8.99,9,9,9])

In [28]:
dataframe

dept    name  roll  cgpa2  cgpa1
0   IT  Anupam    55   9.20    9.0
1   IT      PB    27   9.20    9.0
2   IT      PJ    25   9.30    9.0
3   IT      DK    27   9.60    9.0
4   36      MS    36   8.90    8.0
5   IT  Prerna    26   8.80    8.0
6   IT      KV    40   8.99    8.0
7   IT      pC    28   9.00    7.5
8   IT      SV     4   9.00    7.5
9   IT      MB    37   9.00    7.5